package com.shelfwise.backend.modules.books.models;

public enum Genre {
    FICTION,
    NON_FICTION,
    MYSTERY,
    THRILLER,
    FANTASY,
    SCIENCE_FICTION,
    ROMANCE,
    HISTORICAL,
    BIOGRAPHY,
    AUTOBIOGRAPHY,
    SELF_HELP,
    PHILOSOPHY,
    POETRY,
    DRAMA,
    COMICS,
    GRAPHIC_NOVEL,
    CHILDREN,
    YOUNG_ADULT,
    RELIGION,
    SPIRITUALITY,
    SCIENCE,
    TECHNOLOGY,
    EDUCATION,
    BUSINESS,
    ECONOMICS,
    POLITICS,
    LAW,
    TRAVEL,
    COOKING,
    ART,
    MUSIC,
    HEALTH,
    SPORTS,
    HORROR
}
